- name: Example Playbook
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print message
      debug:
        msg: "Hello, Ansible!"
    - name: install net-tools
      apt:
        name: net-tools
        state: present
